### ISSUE TITLE
Cannot regenerate same results

### ISSUE THREAD

**Issue by harsh-amenity** [riponazad/echotracker#1]
@androst @artemcher @riponazad @sigurdwifstad 
Thank you for your wonderful contribution. This method can help doctors track the features while examining the patients.

I had an issue while testing your code and model. Below is [Your results](https://github.com/riponazad/echotracker/assets/140482649/bbca77e6-1eb4-4b7f-b5a1-1c39f20f9107) which looks perfect. But when I tried to recreate the results it gave me output like this [my results](https://github.com/riponazad/echotracker/assets/140482649/b310e5dd-8964-43ca-a2ae-0813174ee8fa)

Can you tell me which things may have gone wrong?

Thanks again.!!

**Comment by riponazad** [comment]
Hello @harsh-amenity,
Thanks for the appreciation. I have reproduced the issue you are facing and figured out that you are just missing to load the pretrained weights. Just follow the [initial instruction](https://github.com/riponazad/echotracker?tab=readme-ov-file#run-demos) immediately before demo1.

I am sure this will resolve the issue. Please let me know how it goes.

Regards, 
Azad

**Comment by harsh-amenity** [comment]
@riponazad 
These are the logs. It shows that the model is being loaded.
![image](https://github.com/riponazad/echotracker/assets/140482649/0ad3a65e-c0f9-4858-a584-23074e85253b)

**Comment by riponazad** [comment]
![338242230-0ad3a65e-c0f9-4858-a584-23074e85253b](https://github.com/riponazad/echotracker/assets/39602054/6ced284c-5207-46f5-997a-3d1fcfd178b0)
You see here? It says there is no full checkpoint here. 
First, download the checkpoint from [here](https://drive.google.com/file/d/1FJmNlfE5lNPSpBbtnc3KBOgC7cp6DCpl/view?usp=drive_link).
Then move this model_0000000.pth file into the weight folder. And then finally, you can run the demo safely.

**Comment by harsh-amenity** [comment]
@riponazad 
Yes, it worked. It was my mistake. 
In a hurry, I have placed the model into "model/" instead of "model/weights/"
Thank you for your time and quick responses.

**Comment by riponazad** [comment]
That's great to here. Let us know how it goes. We are desperately trying to improve it for the upcoming version.
